version: '3.8'

services:
  # WhatsApp Bot com Baileys (mais simples)
  whatsapp-bot:
    build: .
    container_name: whatsapp-financial-bot
    ports:
      - "3001:3001"
    volumes:
      - ./sessions:/app/sessions
      - ./qr-codes:/app/qr-codes
    environment:
      - NODE_ENV=production
      - N8N_WEBHOOK_URL=https://seu-n8n.com/webhook/whatsapp-webhook
      - BOT_NAME=Assistente Financeiro
      - PORT=3001
    restart: unless-stopped
    networks:
      - whatsapp-network

  # Interface Web para ver QR Code e status
  whatsapp-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: whatsapp-dashboard
    ports:
      - "3002:3002"
    volumes:
      - ./sessions:/app/sessions
      - ./qr-codes:/app/qr-codes
    environment:
      - BOT_SERVICE=whatsapp-bot:3001
    restart: unless-stopped
    networks:
      - whatsapp-network
    depends_on:
      - whatsapp-bot

networks:
  whatsapp-network:
    driver: bridge

volumes:
  sessions:
  qr-codes:
